<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.6.5.2 setup script
 * Date: Fri, 23 Dec 2016 16:18:07 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: scalingo [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'scalingo';
$cfg['Servers'][$i]['host'] = 'test-play2c-5334.mysql.dbs.appsdeck.eu';
$cfg['Servers'][$i]['port'] = 30973;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '!mmQAj^t?{gzsEnAU5Eh7n&vmUyrdA3u';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>